import {planDocument} from './checkup-download.mjs?v=1';
import {questions,assess,tailoredPlan,label} from './checkup-engine.mjs?v=4';
const $=id=>document.getElementById(id),key='bmt-free-checkup-v1';
let answers={},current=0,started=false,completed=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function prune(){const qs=questions(answers),allowed=new Set(qs.map(q=>q.id));for(const k of Object.keys(answers))if(!allowed.has(k))delete answers[k];for(const q of qs){if(q.options&&answers[q.id]&&!q.options.some(o=>o[0]===answers[q.id]))delete answers[q.id];if(q.type==='text'&&typeof answers[q.id]!=='string')delete answers[q.id];}}
function save(){if(!$('remember').checked)return;try{localStorage.setItem(key,JSON.stringify({answers,current}));$('save-status').textContent='Progress saved on this device.';}catch{$('save-status').textContent='Your browser could not save this draft. Keep the tab open or download the finished plan.';}}
try{const raw=localStorage.getItem(key);if(raw){const saved=JSON.parse(raw);if(saved.answers&&typeof saved.answers==='object'&&!Array.isArray(saved.answers)){for(const [k,v] of Object.entries(saved.answers))if(typeof v==='string')answers[k]=v.slice(0,160);prune();current=Math.max(0,Math.min(Number.isInteger(saved.current)?saved.current:0,questions(answers).length-1));const firstMissing=questions(answers).findIndex(q=>q.options&&!answers[q.id]);if(firstMissing>=0)current=Math.min(current,firstMissing);$('remember').checked=true;$('save-status').textContent='Your saved answers have been restored.';}}}catch{$('save-status').textContent='The saved draft could not be restored. You can start a new checkup.';}
function event(name){document.dispatchEvent(new CustomEvent('bmt:checkup',{detail:{event:name}}));}
function render(focus=false){
 const qs=questions(answers);current=Math.max(0,Math.min(current,qs.length-1));const q=qs[current];
 $('questionnaire').hidden=false;$('results').hidden=true;$('checkup-intro').hidden=current>0;
 $('step-label').textContent=`Question ${current+1} of ${qs.length}`;$('section-label').textContent=current<5?'Your business':current<9?'Your direction':'Finding a useful next step';$('progress').value=Math.round(current/qs.length*100);
 const box=$('question');box.dataset.question=q.id;box.replaceChildren();const h=el('h2',q.title);h.id='question-title';h.tabIndex=-1;box.append(h);
 if(q.help){const help=el('p',q.help,'question-help');help.id='question-help';box.append(help);}
 if(q.type==='text'){
  const input=el('input');input.type='text';input.id='text-answer';input.className='answer-text';input.maxLength=q.id==='location'?80:160;input.value=answers[q.id]||'';input.setAttribute('aria-labelledby','question-title');input.setAttribute('aria-describedby','question-help');input.autocomplete='off';
  input.addEventListener('input',()=>{answers[q.id]=input.value;save();});box.append(input);
 }else{
  const choices=el('div',undefined,'choices'+(q.id==='trade'?' trade-options':''));choices.setAttribute('role','group');choices.setAttribute('aria-labelledby','question-title');if(q.help)choices.setAttribute('aria-describedby','question-help');
  for(const [value,text] of q.options){const button=el('button',text,'choice');button.type='button';button.dataset.value=value;button.setAttribute('aria-pressed',String(answers[q.id]===value));button.addEventListener('click',()=>{answers[q.id]=value;prune();$('answer-error').hidden=true;choices.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('next').textContent=current===questions(answers).length-1?'See my free plan →':'Continue →';$('step-label').textContent=`Question ${current+1} of ${questions(answers).length}`;save();if(!started){started=true;event('start');}});choices.append(button);}box.append(choices);
 }
 $('back').hidden=current===0;$('next').textContent=current===qs.length-1?'See my free plan →':'Continue →';$('answer-error').hidden=true;
 if(focus){h.focus({preventScroll:true});$('questionnaire').scrollIntoView({block:'start',behavior:'instant'});}
}
function section(title){const s=el('section',undefined,'result-section');s.append(el('h2',title));return s;}
function anchor(text,href,cls){const a=el('a',text,cls);a.href=href;return a;}
function list(items,ordered=false){const l=el(ordered?'ol':'ul',undefined,ordered?'plan-steps':'');items.forEach(t=>l.append(el('li',t)));return l;}
function planText(){const r=assess(answers),p=tailoredPlan(answers,r);return ['BLACK MOUNTAIN TECHNOLOGIES — FREE BUSINESS CHECKUP',new Date().toLocaleDateString(),'','SUGGESTED STARTING POINT',p.title,p.explanation,'',...r.reasons,'',r.limits,'','YOUR NEXT STEPS',...p.actions.map((t,i)=>`${i+1}. ${t}`),'',...p.notes,'',...(p.remedies.length?['WAYS TO TACKLE THE CHALLENGE',...p.remedies.flatMap(item=>[item.title,...item.steps.map((t,i)=>`${i+1}. ${t}`),...item.scripts.map(script=>`${script.label}: ${script.text}`),'Track: '+item.track,''])]:[]),'','WHAT TO TRACK',p.metric,'','YOUR ANSWERS',...questions(answers).map(q=>`${q.title}\n${label(answers,q.id)}`),'','Free guides: https://blackmountaintech.ca/free-advice.html','Questions: michael@blackmountaintechnologies.ca'].join('\n');}
function result(){
 prune();const r=assess(answers),p=tailoredPlan(answers,r),box=$('results');box.replaceChildren();$('questionnaire').hidden=true;$('checkup-intro').hidden=true;box.hidden=false;
 const lead=el('div',undefined,'result-lead');lead.append(el('p','YOUR FREE ACTION PLAN','eyebrow'));const h=el('h1',p.title);h.id='result-title';h.tabIndex=-1;lead.append(h,el('p',p.explanation,'intro'),el('p',r.limits,'limits'));box.append(lead);
 const context=section('Where you are. Where you want to go.');const dl=el('dl',undefined,'facts');
 for(const [term,value] of [['Your work',label(answers,'trade')],['Your area',[label(answers,'country'),answers.location].filter(Boolean).join(' · ')],['Business stage',label(answers,'stage')],['Your team',label(answers,'team')],...(answers.revenue?[['Current monthly revenue',label(answers,'revenue')+(answers.country==='ca'?' CAD':answers.country==='us'?' USD':' (local currency)')]]:[]),['Your goal',label(answers,'goal')],...(answers.goal_detail?[['Success looks like',answers.goal_detail]]:[]),['Your chosen timeframe',label(answers,'timeline')]]){const d=el('div');d.append(el('dt',term),el('dd',value));dl.append(d);}context.append(dl);box.append(context);
 const why=section('Why this is the suggested starting point');why.append(list(r.reasons));if(answers.pain&&answers.pain!=='unknown'&&answers.pain!==r.primary){why.append(el('p',`You chose “${label(answers,'pain')}” as your concern. Your other answers suggest checking the priority above first. That does not rule out your original concern.`));}box.append(why);
 const actions=section('Three practical next steps');actions.append(list(p.actions,true));if(p.notes.length){actions.append(el('h3','A few details from your answers'),list(p.notes));}box.append(actions);
 if(p.remedies.length){const remedies=section('Ways to tackle this challenge');remedies.classList.add('remedies');remedies.append(el('p','Open the situations that fit. Start with one or two actions and track what happens. These are practical options, not a promise of more work.'));for(const item of p.remedies){const detail=el('details',undefined,'remedy');detail.append(el('summary',item.title));const body=el('div',undefined,'remedy-body');body.append(list(item.steps,true));if(item.scripts.length){body.append(el('h3','Words you can use'));for(const script of item.scripts){body.append(el('p',script.label,'script-label'),el('blockquote',script.text,'example-script'));}}body.append(el('p','Track: '+item.track,'remedy-track'));detail.append(body);remedies.append(detail);}box.append(remedies);}
 const track=section('How to tell whether it is helping');track.append(el('p',p.metric),el('p','Record your starting point before making changes. Review it weekly; allow for seasonality and your normal sales and project timelines.'));box.append(track);
 if(r.secondary.length){const s=section('Also worth checking');for(const other of r.secondary){s.append(el('h3',({pipeline:'Lead flow and winning suitable jobs',pricing:'Job costs and quoting',cash:'Payments and cash flow',capacity:'Workload and coordination',conversion:'Quote follow-up',leads:'Suitable inquiries',measurement:'Tracking the numbers'})[other.key]),el('p',other.reasons.join(' ')));}box.append(s);}
 const resources=section('Use the free resources');const links=el('div',undefined,'resource-links');for(const [text,url] of p.links)links.append(anchor(text+' ↗',url));resources.append(links);box.append(resources);
 const buttons=el('div',undefined,'result-actions');const download=el('button','Download my plan','button');download.type='button';download.addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([planDocument(box)],{type:'text/html;charset=utf-8'}));const a=anchor('',url);a.download='BMT-business-action-plan.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 const edit=el('button','Review / change my answers','quiet');edit.type='button';edit.addEventListener('click',()=>{current=0;render(true);});buttons.append(download,edit);box.append(buttons,el('p','Downloads a formatted plan you can open in your browser, read offline, or print and save as a PDF.','download-note'));
 const details=el('details',undefined,'answer-review');details.append(el('summary','See all my answers'));const all=el('dl');questions(answers).forEach(q=>all.append(el('dt',q.title),el('dd',label(answers,q.id))));details.append(all);box.append(details);
 const help=el('section',undefined,'paid-help');help.append(el('p','OPTIONAL PERSONAL HELP','eyebrow'),el('h2','Want a second set of eyes?'),el('p','Use this plan yourself, or work through it with Michael. A $100 CAD business review includes pre-call questions, a 30-minute consultation, and a written 30-day action plan.'));
 help.append(anchor('Book a business review · $100 CAD','https://buy.stripe.com/6oUdR9bJm4eCcL90vt3cc0f','button'),el('p','One-time payment. Michael arranges your questions and session time by email after payment. Your checkup answers are not automatically sent with payment.','fine'));
 const mail=el('button','Email Michael my answers ↗','text-button');mail.type='button';mail.addEventListener('click',()=>{window.location.href='mailto:michael@blackmountaintechnologies.ca?subject='+encodeURIComponent('My contractor business checkup')+'&body='+encodeURIComponent(planText());});help.append(mail,el('p','Opens your email app with your plan. You review it and choose whether to send. Save a download if your email app cannot open the full draft.','fine'),el('p','Coaching, websites and automation are options when they fit the problem. You do not need to buy them to use your plan.','fine'));box.append(help);
 const reset=el('button','Start a new checkup','text-button');reset.type='button';reset.addEventListener('click',restart);box.append(reset);h.focus({preventScroll:true});box.scrollIntoView({block:'start',behavior:'instant'});save();if(!completed){completed=true;event('complete');}
}
$('checkup-form').addEventListener('submit',e=>{e.preventDefault();const qs=questions(answers),q=qs[current];if(q.options&&!answers[q.id]){$('answer-error').hidden=false;$('question').querySelector('button')?.focus();return;}if(current===qs.length-1)result();else{current++;render(true);save();}});
$('back').addEventListener('click',()=>{current--;render(true);save();});
$('remember').addEventListener('change',()=>{if($('remember').checked)save();else{try{localStorage.removeItem(key);$('save-status').textContent='Saved copy removed. Answers remain in this open tab.';}catch{$('save-status').textContent='Could not clear the saved copy. Clear this site’s browser data to remove it.';}}});
function restart(){if(!confirm('Clear these answers and start a new checkup?'))return;answers={};current=0;started=false;completed=false;$('remember').checked=false;try{localStorage.removeItem(key);$('save-status').textContent='Answers cleared.';}catch{$('save-status').textContent='Answers cleared here. Clear site data to remove any saved browser copy.';}render(true);}
$('restart').addEventListener('click',restart);render();
