// Transparent decision rules, not a trained or clinically validated diagnostic model.
export const trades = [
 ['concrete','Concrete','forms, reinforcement, access, pumping and finishing'],
 ['excavation','Excavation & drainage','access, ground conditions, disposal, equipment and utility locating'],
 ['landscape','Landscaping & hardscaping','base preparation, drainage, materials, access and disposal'],
 ['fencing','Fencing & gates','layout, post holes, materials, access and removal'],
 ['decks','Decks & outdoor structures','design, footings, materials, access and finishing'],
 ['renovation','Renovations & general contracting','scope, subcontractors, materials, site protection and changes'],
 ['roofing','Roofing & siding','access, removal, disposal, materials and weather delays'],
 ['plumbing','Plumbing','diagnosis, parts, access, travel and return visits'],
 ['hvac','Heating & cooling','equipment, parts, access, commissioning and return visits'],
 ['electrical','Electrical','scope, materials, access, testing and return visits'],
 ['painting','Painting & drywall','preparation, repairs, protection, materials and cleanup'],
 ['masonry','Masonry','preparation, access, materials, scaffolding and cleanup'],
 ['paving','Paving & asphalt','base preparation, drainage, access, materials and equipment'],
 ['tree','Tree services','access, equipment, removal, disposal and site protection'],
 ['cleaning','Cleaning & property maintenance','property size, condition, travel, supplies and service frequency'],
 ['other','Another trade','labour, materials, equipment, travel, overhead and scope changes']
];
const q=(id,title,options,help='')=>({id,title,options:options.map(x=>Array.isArray(x)?x:[x,x]),help});
const unknown=['unknown',"I’m not sure"];
export const plans={
 launch:{title:'Prove one clear service before building everything.',explanation:'A focused first offer gives you something specific to price, explain and test with customers.',actions:['Choose one service and a realistic service area. Write down who it helps and what is included.','Build a sample quote with labour, materials, equipment and overhead. Check local requirements before accepting work.','Talk with five potential customers or referral partners. Record the questions and objections before spending on a bigger launch.'],metric:'Qualified inquiries, quotes sent and the outcome of each conversation.',links:[['Getting leads','/free-game/getting-leads.html'],['Quoting and contract','/free-game/quoting-and-contract.html']]},
 leads:{title:'Build a steadier flow of suitable inquiries.',explanation:'Start with one clear service and one lead source you can measure. More inquiries only help if the work fits and you have room for it.',actions:['Define your best-fit job, service area and the jobs you will decline.','Check that your website and business profile clearly show your services, area, recent work and how to contact you.','Choose one channel for a small test. Track qualified inquiries and quotes from it before increasing effort or spending.'],metric:'Qualified inquiries by source, and how many become quoted jobs.',links:[['All 22 lead sources','/free-advice.html#getting-leads'],['Lead tracker and templates','/free-game/templates.html']]},
 pipeline:{title:'Work on both sides: more suitable leads, more jobs from your quotes.',explanation:'A quiet calendar can have two separate causes: too few suitable inquiries and too few quotes turning into work. Check both rather than relying on more advertising or lower prices alone.',actions:['Build two lists: recent inquiries by source, and open or recently lost quotes. Separate undecided customers from confirmed losses, and record any reason they actually gave.','Work the quotes already in play. Ask whether the project is still going ahead, what is holding up the decision, and when a follow-up would be useful. Make scope, proof of your work and the acceptance step easy to understand.','At the same time, test one focused way to reach suitable customers: past-client relationships, local referral partners, or a clearer local business profile. Track inquiries through to jobs won before increasing spending.'],metric:'Suitable inquiries by source; quotes sent; won, lost and still-open quotes; confirmed loss reasons; and profit on jobs won. Compare similar periods and allow for seasonality.',links:[['Ways to get leads','/free-advice.html#getting-leads'],['Closing the deal','/free-game/closing-the-deal.html'],['Follow-up templates','/free-game/templates.html']]},
 conversion:{title:'Find out why quotes aren’t turning into jobs.',explanation:'A quote needs a clear next step. Learn what is holding the customer back before assuming you need more leads or lower prices.',actions:['List every open quote, when it was sent and the next agreed follow-up.','Contact customers who are expecting a follow-up. Ask what they need to make a decision, then record their answer.','Track won, lost and undecided quotes separately. Review scope, timing, trust and price objections before considering automation.'],metric:'Open quotes with a next action; won/lost decisions and the reasons behind them.',links:[['Closing the deal','/free-game/closing-the-deal.html'],['Follow-up templates','/free-game/templates.html']]},
 pricing:{title:'Check what your jobs actually leave you.',explanation:'Revenue alone cannot tell you whether a job made money. Compare the price with actual costs before trying to grow faster.',actions:['Review three completed jobs. Include your own labour, crew time, materials, rentals, disposal and subcontractors.','Compare each estimate with actual costs. Account for overhead and note any unpaid extras or scope changes.','Update your quoting checklist using the largest misses. Explain and agree on changes before doing extra work.'],metric:'Estimated versus actual job costs, gross profit, and unpaid extras. Gross profit is not net profit.',links:[['Job pricing tools','/free-game/tools.html'],['Quoting and contract','/free-game/quoting-and-contract.html']]},
 cash:{title:'Get a clear picture of money due in and out.',explanation:'Late payments and near-term bills need attention before adding new commitments. The first step is knowing amounts and dates.',actions:['List unpaid invoices, due dates, disputed amounts and expected payment dates.','Map the next four weeks of payroll, materials and other bills against expected collections. Follow up on overdue invoices using your agreed terms.','Review billing milestones and payment terms for future work. If essential bills cannot be covered, speak promptly with your accountant and the affected parties.'],metric:'Overdue invoices, expected collection dates and the next four weeks of cash commitments.',links:[['Quoting and payment terms','/free-game/quoting-and-contract.html'],['Completion and collection','/free-game/after-completion.html']]},
 capacity:{title:'Make room to deliver before adding more work.',explanation:'A full schedule can hide a coordination or workload problem. Fixing delivery pressure helps protect the jobs you already sold.',actions:['Map active jobs, crew availability and promised dates for the next two weeks. Flag conflicts before they become delays.','Identify the work only you can do. Give repeatable tasks a clear owner and a short checklist.','Track where time goes for a week. Fix the biggest repeated delay before committing to hiring, advertising or more bookings.'],metric:'Jobs finished when promised, rework hours, and owner hours spent on admin.',links:[['Pre-work planning','/free-game/pre-work.html'],['Running the work','/free-game/the-work-itself.html']]},
 measurement:{title:'Get a simple baseline before choosing a fix.',explanation:'There is not enough clear information here to call one issue your main bottleneck. A small amount of tracking will make the next decision more useful.',actions:['For the next two weeks, record inquiries, quotes, outcomes and the source of each lead in one place.','Review three recent jobs for estimated versus actual costs. Keep unpaid invoices and due dates visible.','Set a weekly 20-minute review. Use the numbers to choose one change, then compare results over a relevant period.'],metric:'A complete weekly lead, quote, job-cost and payment record.',links:[['Free tracking templates','/free-game/templates.html'],['How to review your week','/free-game/how-to.html']]},
 healthy:{title:'Test your next goal without disrupting what works.',explanation:'Your answers do not reveal a clear operational problem. This is a starting point, not proof that every part of the business is healthy.',actions:['Choose one measurable goal and record your current starting point.','Run one small change that supports that goal. Keep service quality, capacity and job profitability visible.','Review the change after enough time for your usual sales or job cycle. Keep what helps and adjust what does not.'],metric:'Your chosen goal alongside job profitability, workload and customer outcomes.',links:[['The contractor playbook','/free-advice.html'],['Weekly scorecard','/downloads/weekly-business-scorecard.csv']]}
};
export function assess(a){
 if(a.stage==='planning')return {primary:'launch',reasons:['You said you are planning your first contracting business.'],secondary:[],unknowns:0,limits:'This is a launch checklist, not a forecast of demand or earnings.'};
 const signals=[];
 const push=(key,weight,reason)=>signals.push({key,weight,reason});
 if(a.payment==='blocked')push('cash',10,'You said overdue customer payments are making it hard to cover bills.');
 else if(a.payment==='late')push('cash',4,'You said overdue invoices regularly tie up cash.');
 if(a.jobcost==='losses')push('pricing',9,'You said recent jobs often leave too little money or lose money.');
 if(a.capacity==='overloaded')push('capacity',8,'You said the workload is causing delays or constant catch-up.');
 if(a.jobcost==='unknown')push('measurement',6,'You do not yet know what completed jobs cost or leave you.');
 const quoteLoss=['ghost','cheaper','mixed','postponed'].includes(a.quote_outcome);
 if(quoteLoss)push('conversion',5,a.quote_outcome==='cheaper'?(a.c_comparison==='assumed'?'You suspect price is behind lost quotes, but said that has not been confirmed.':'You reported often losing quotes to a lower price; the comparison still needs checking.'):a.quote_outcome==='postponed'?'You said customers often postpone or cancel the project.':'You said too many quotes go quiet or do not turn into work.');
 if(a.leadflow==='few'&&quoteLoss)push('pipeline',6.5,'You reported both too few suitable inquiries and difficulty turning quotes into work.');
 if(a.followup==='none'||a.followup==='sometimes')push('conversion',5,'You said quote follow-up is missing or inconsistent.');
 if(a.leadflow==='few'&&a.capacity!=='overloaded')push('leads',5,'You said you need more suitable inquiries to fill available work time.');
 if(a.capacity==='admin')push('capacity',4,'You said admin keeps pushing into your evenings.');
 if(a.scope==='no')push('pricing',4,'You said trade-specific costs or scope details are being missed in quotes.');
 if(a.jobcost==='estimate')push('pricing',3,'You estimate job costs but do not consistently compare them with actual costs.');
 if(a.c_reason==='scope')push('conversion',4,'You said customers often need more clarity on what the quote includes.');
 if(a.c_reason==='price')push('conversion',5,'Customers raise price objections. Check the comparison before assuming your price is wrong.');
 if(a.c_reason==='silent')push('conversion',5,'You said customers stop responding after the quote.');
 if(a.p_owner==='no')push('pricing',7,'Your own labour is not included in job costing.');
 if(a.p_changes==='absorbed')push('pricing',6,'You said you often absorb the cost of added work.');
 if(a.c_approval==='no')push('conversion',3,'Your quotes do not have a consistent next step for acceptance.');
 if(a.m_invoice==='late')push('cash',3,'Invoices often go out days or weeks after the billing milestone.');
 if(a.w_time==='rework')push('capacity',5,'You identified mistakes or rework as an avoidable time drain.');
 const grouped=new Map();for(const s of signals){if(!grouped.has(s.key))grouped.set(s.key,{key:s.key,weight:s.weight,reasons:[]});const g=grouped.get(s.key);g.weight=Math.max(g.weight,s.weight);g.reasons.push(s.reason);}
 const sorted=[...grouped.values()].filter(s=>!grouped.has('pipeline')||!['leads','conversion'].includes(s.key)).sort((x,y)=>y.weight-x.weight);
 const unknowns=['leadflow','quote_outcome','followup','jobcost','payment','capacity'].filter(k=>!a[k]||a[k]==='unknown'||a[k]==='not_yet').length;
 if(unknowns>=3&&!sorted.some(s=>s.weight>=8))return {primary:'measurement',reasons:['Several key parts of your lead, cost or workload picture are not yet clear.'],secondary:sorted.filter(s=>s.key!=='measurement').slice(0,2),unknowns,limits:'There is not enough information to confidently identify the main problem. Start by measuring.'};
 if(!sorted.length){const key=unknowns?'measurement':'healthy';return {primary:key,reasons:[unknowns?'A key part of the picture is still unknown.':'You reported enough inquiries and jobs won for your goals, consistent follow-up, tracked job costs, manageable payments and a manageable workload.'],secondary:[],unknowns,limits:'Based only on your answers. Customer conversations and actual job records may show a different priority.'};}
 return {primary:sorted[0].key,reasons:sorted[0].reasons,secondary:sorted.slice(1,3),unknowns,limits:unknowns?'Some answers are unknown. Check the missing information before making a larger commitment.':'This is a suggested starting point based on your answers, not a verified audit or a promise of results.'};
}
export function branch(a){const baseline=Object.fromEntries(['stage','leadflow','quote_outcome','followup','jobcost','payment','capacity'].map(k=>[k,a[k]]));if(a.pain==='pipeline'||(['leads','conversion','unknown'].includes(a.pain)&&a.leadflow==='few'&&['ghost','cheaper','mixed','postponed'].includes(a.quote_outcome)))return 'pipeline';return ['leads','conversion','pricing','cash','capacity'].includes(a.pain)?a.pain:assess(baseline).primary;}
export function questions(a){
 const trade=trades.find(t=>t[0]===a.trade)||trades.at(-1);
 const qs=[q('trade','What kind of work do you do?',trades.map(t=>[t[0],t[1]]),'Choose your main trade. We’ll tailor the examples to your work.'),q('stage','Where is the business today?',[['planning','Planning to start'],['new','In business for less than a year'],['established','In business for a year or more']]),q('country','Where do you work?',[['ca','Canada'],['us','United States'],['other','Somewhere else']]),{id:'location',title:'What city or area do you serve?',type:'text',help:'Optional. A city, province or state is enough. No street address needed.'},q('team','Who is doing the work?',[['solo','Just me'],['small','Me and 1–2 others'],['crew','4–10 people'],['larger','More than 10 people']])];
 if(a.stage!=='planning')qs.push(q('revenue','Roughly what is your monthly revenue?',[['zero','No revenue yet'],['under10','Under $10,000'],['10to25','$10,000–$25,000'],['25to50','$25,000–$50,000'],['50to100','$50,000–$100,000'],['over100','Over $100,000'],unknown],`Use a typical month, not your best month. Revenue is sales before costs. ${a.country==='ca'?'Amounts in CAD.':a.country==='us'?'Amounts in USD.':'Use your local currency; no currency conversion is applied.'}`));
 qs.push(q('goal','What would a better business look like to you?',[['profit','More profit from the work I do'],['steady','Steadier work and income'],['time','Less time on admin and evenings'],['grow','A bigger business and team'],['start','A clear path to my first jobs']]),{id:'goal_detail',title:'What would success look like in real terms?',type:'text',help:'Optional. For example: $40,000 a month in sales, two profitable jobs a week, or getting my evenings back. Use your local currency.'},q('timeline','When do you want to make progress?',[['month','Over the next 30 days'],['quarter','Over the next 3 months'],['year','Over the next year']],'This helps frame your plan. It is not a promised deadline for results.'));
 if(a.stage==='planning'){
  qs.push(q('launch_service','Have you chosen a service and customer?',[['yes','Yes, both are clear'],['partial','I know my trade, but not my ideal jobs'],['no','I’m still deciding']]),q('launch_validation','Have you spoken with potential customers?',[['yes','Yes, I have real inquiries'],['some','A few conversations, no clear demand yet'],['no','Not yet']]),q('launch_pricing','Have you worked out what a job would cost?',[['yes','Yes, including my time and overhead'],['some','Some costs, but not the whole picture'],['no','Not yet']]));return qs;
 }
 qs.push(q('pain','What feels like the biggest problem?',[['pipeline','Not enough leads, and losing the ones I get'],['leads','Not enough good leads'],['conversion','Quotes don’t turn into jobs'],['pricing','Busy, but not enough profit'],['cash','Money comes in too slowly'],['capacity','Too much work or admin'],['unknown','I’m not sure where the problem is']],'We’ll check this against the rest of your answers rather than assume it is the root cause.'),q('leadflow','Are enough suitable inquiries coming in?',[['few','No, I have room for more suitable work'],['steady','Yes, enough for my current capacity'],['too_many','More than I can comfortably handle'],unknown]),q('quote_outcome','What is happening with the quotes you send?',[['winning','Enough turn into work for my current goals'],['ghost','Too many customers stop responding'],['cheaper','We often lose to a cheaper quote'],['postponed','Customers often postpone or cancel the project'],['mixed','A mix of ghosting, cheaper quotes and delays'],['not_yet','I haven’t sent enough quotes to tell'],unknown],'Choose the pattern you are seeing. A customer who has not decided is not yet a confirmed lost job.'),q('followup','What happens after you send a quote?',[['consistent','Every open quote has a planned follow-up'],['sometimes','I follow up when I have time'],['none','Mostly wait for the customer'],unknown]),q('jobcost','Do you know what your completed jobs leave you?',[['tracked','I compare actual costs with the quote'],['estimate','I estimate it, but don’t track it consistently'],['losses','I track it; jobs often leave too little or lose money'],unknown]),q('payment','Are customer payments creating a problem?',[['okay','No, payments are manageable'],['late','Overdue invoices regularly tie up cash'],['blocked','Late payments are making bills hard to cover'],unknown]),q('capacity','How manageable is the workload?',[['room','There is room for more work'],['balanced','Busy, but manageable'],['admin','The work is manageable; admin eats my evenings'],['overloaded','Delays and constant catch-up'],unknown]));
 const b=branch(a);
 const demand=q('demand','How does demand compare with your normal season?',[['lower','Noticeably quieter than a comparable period'],['same','About the same, but not enough for my goals'],['new','Too new to compare'],unknown],'Think about similar weather, season and services. This does not prove the whole market is slowing down.');
 const source=q('l_source','Where do most inquiries come from?',[['referral','Referrals and past customers'],['google','Google or my website'],['social','Social media or local groups'],['ads','Paid ads'],['mixed','A mix of sources'],unknown]);
 const reason=q('c_reason','What do customers actually tell you when they don’t go ahead?',[['price','They say another quote is cheaper'],['scope','They need clarity on scope or value'],['timing','They say the timing or budget changed'],['silent','They go quiet; I don’t know why'],['mixed','Different reasons for different customers'],unknown]);
 const priceProof=q('c_comparison','How much do you know about the cheaper competing quote?',[['comparable','The customer shared it; scope looks comparable'],['different','The scope, materials or inclusions differ'],['reported','They said it was cheaper; I haven’t seen the details'],['assumed','I’m assuming price because they went quiet'],['not_price','Price has not been raised'],unknown],'Compare agreed work and inclusions. A lower price can be genuine competition; silence alone is not evidence of undercutting.');
 const qualification=q('c_fit','Before pricing, do you discuss scope, budget and timing?',[['yes','Usually, before spending time on the quote'],['some','Sometimes, but not consistently'],['no','Mostly just send the price']]);
 const follow={
  pipeline:[demand,source,reason,priceProof,qualification],
  leads:[demand,q('l_source','Where do most inquiries come from?',[['referral','Referrals and past customers'],['google','Google or my website'],['social','Social media or local groups'],['ads','Paid ads'],['mixed','A mix of sources'],unknown]),q('l_tracking','Can you tell which sources bring profitable jobs?',[['yes','Yes, I track sources and job results'],['partial','I know the source, but not the job result'],['no','No, I don’t track that']])],
  conversion:[reason,priceProof,qualification,q('c_approval','Is the next step clear on your quotes?',[['yes','Yes: scope, terms and how to accept'],['partial','Some of it is clear'],['no','No consistent next step']])],
  pricing:[q('p_owner','Does your job costing include your own labour?',[['yes','Yes, alongside the crew’s time'],['no','No, I mainly count what I pay others'],unknown]),q('p_changes','How do you handle work added after the quote?',[['written','Agree on price and scope before doing it'],['verbal','Usually a verbal agreement'],['absorbed','Often just do it and absorb the cost']])],
  cash:[q('m_invoice','When do you usually send invoices?',[['prompt','As soon as an agreed milestone is reached'],['late','Often a few days or weeks later'],['end','Usually only at the end of the project']]),q('m_terms','Are payment dates and milestones agreed in writing?',[['yes','Yes, before work starts'],['sometimes','Sometimes'],['no','Not consistently']])],
  capacity:[q('w_time','What takes up the most avoidable time?',[['admin','Messages, quotes and chasing people'],['schedule','Scheduling, materials and coordination'],['rework','Mistakes, rework or unclear instructions'],['delivery','More on-site work than the team can handle'],unknown]),q('w_owner','Do repeatable tasks have a clear owner and checklist?',[['yes','Mostly yes'],['some','Some do'],['no','Most things still come back to me']])],
  measurement:[q('u_records','Where are your leads, quotes and job costs recorded?',[['one','One place, but I don’t review it'],['scattered','Across messages, notes and software'],['none','Mostly in my head']])],
  healthy:[q('h_next','Which next step are you considering?',[['service','Improve or add a service'],['marketing','Test a new lead source'],['systems','Make a working process easier'],['unsure','I’m still deciding']])]
 };
 qs.push(...(follow[b]||follow.measurement));
 qs.push(q('scope',`Do your quotes cover the details that affect your ${trade[1].toLowerCase()} jobs?`,[['yes','Yes, I check these before pricing'],['no','Some get missed or become unpaid extras'],unknown],`For example: ${trade[2]}. Requirements vary by job and location.`));return qs;
}
export function label(a,id){const question=questions(a).find(q=>q.id===id);return question?.options?.find(o=>o[0]===a[id])?.[1]||a[id]||'Not provided';}

export function tailoredPlan(a,result=assess(a)) {
 const base=plans[result.primary];const out={...base,actions:[...base.actions],notes:[]};
 if(['pricing','launch'].includes(result.primary)){const trade=trades.find(t=>t[0]===a.trade)||trades.at(-1);out.notes.push(`For ${trade[1].toLowerCase()}, check ${trade[2]} when building the quote.`);}
 if(result.primary==='launch'){
  if(a.launch_service!=='yes')out.notes.push('Your service or ideal customer is still being defined. Start there.');
  if(a.launch_validation==='no')out.notes.push('You have not tested demand in customer conversations yet.');
  if(a.launch_pricing!=='yes')out.notes.push('Your first job-cost model still needs work before accepting a price.');
 }
 if(result.primary==='leads'&&a.l_source==='ads')out.actions[2]='Review your existing ads from inquiry through quote to job outcome. Separate lead quality from follow-up problems before increasing the budget.';
 if(result.primary==='leads'&&a.l_source==='referral')out.actions[2]='Keep referrals working, then test one additional source. Ask satisfied past customers whether they know anyone who needs your service, and track the resulting inquiries.';
 if(a.l_tracking&&a.l_tracking!=='yes')out.notes.push('You are not yet connecting each lead source to completed job results. Add a source column to your tracker.');
 if(a.c_approval&&a.c_approval!=='yes')out.notes.push('Make the scope, terms and acceptance step clear on every quote.');
 if(result.primary==='pipeline'&&a.jobcost==='unknown')out.notes.push('You do not yet know what completed jobs leave you. Track actual costs alongside lead and quote outcomes, and check those costs before offering a lower price.');
 if(result.primary==='conversion'&&['none','sometimes'].includes(a.followup))out.title='Find out why quotes stall, and make follow-up consistent.';
 if(a.quote_outcome==='ghost'||a.c_reason==='silent'||a.c_comparison==='assumed')out.notes.push('Ghosting does not prove you were too expensive. Try: “Hey [name], is this project still on your list, or have plans changed? Happy to clear up anything in the quote.” If they decline or ask you to stop, close the loop.');
 if(a.quote_outcome==='cheaper'||a.c_reason==='price'||['comparable','different','reported'].includes(a.c_comparison)){
  out.notes.push('Before matching a lower price, check the scope, materials, preparation, removal, timing and inclusions. Explain the differences using relevant job photos, customer feedback and a clear written scope.');
  out.notes.push('Know your costs and minimum acceptable margin before changing the price. If the budget does not fit, discuss a genuinely smaller scope or phased work where practical, or decline. Do not remove necessary work just to look cheaper.');
 }
 if(a.c_comparison==='comparable')out.notes.push('If the competing quote really is comparable, price competition may be real. Review your costs and job fit; stronger follow-up alone will not win every job.');
 if(a.c_comparison==='different')out.notes.push('You said the quotes differ. Show the customer those differences plainly without making unsupported claims about the other contractor.');
 if(a.c_comparison==='reported')out.notes.push('You have a customer-reported lower price, but not the full comparison. Ask what is included before treating it as an equivalent offer.');
 if(a.c_fit&&a.c_fit!=='yes')out.notes.push('Before a detailed site visit or quote, clarify the work, service area, rough budget, timing and who is deciding. This helps you spend quoting time on suitable projects.');
 if(a.demand==='lower')out.notes.push('You reported a quieter comparable period. Review which services still attract inquiries, reconnect with relevant past customers and referral partners, and test one change at a time. This checkup cannot verify market-wide demand or guarantee more work.');
 if(a.quote_outcome==='postponed'||a.c_reason==='timing')out.notes.push('A delayed or cancelled project is different from losing to another contractor. Ask whether and when the customer wants you to check back; do not keep chasing a project they have stopped.');
 if(a.followup==='consistent'&&['ghost','cheaper','mixed'].includes(a.quote_outcome))out.notes.push('You already follow up consistently. Investigate customer fit, clarity, timing and competitive differences rather than simply sending more reminders.');
 if(a.pain==='pipeline'&&a.leadflow!=='few')out.notes.push('You selected a concern about both leads and quotes, but did not confirm too few suitable inquiries. Check that distinction before deciding to buy more leads.');
 if(a.p_owner==='no')out.notes.push('Your own labour is missing from job costing. Include it before judging profitability.');
 if(a.p_changes==='absorbed')out.notes.push('You reported absorbing extras. Agree on added scope and price before doing the work.');
 if(a.p_changes==='verbal')out.notes.push('Put agreed scope changes and prices in writing to avoid misunderstandings.');
 if(a.m_invoice==='late')out.notes.push('Invoice promptly at the agreed milestone; late invoicing delays the start of collection.');
 if(a.m_terms&&a.m_terms!=='yes')out.notes.push('Make payment milestones and due dates clear in your written agreement.');
 if(a.w_time==='rework')out.notes.push('You identified rework as a time drain. Add a quality checkpoint before covering up or completing each stage.');
 if(a.w_time==='schedule')out.notes.push('Confirm materials, equipment and crew availability before promising the next start date.');
 if(a.w_time==='admin')out.notes.push('Write down the repetitive admin task first. A template or checklist may be enough; automation is optional.');
 if(a.w_owner&&a.w_owner!=='yes')out.notes.push('Give one repeatable task a clear owner, checklist and definition of done.');
 if(a.u_records==='one')out.notes.push('You already have a place for the numbers. Add a weekly review before changing software.');
 if(a.leadflow==='too_many'&&a.capacity==='room')out.notes.push('You reported more inquiries than you can handle, but room for more work. Check whether inquiry quality or sales admin explains the difference.');
 if(a.goal==='grow'&&['pricing','cash','capacity','measurement'].includes(result.primary))out.notes.push('You want to grow. Check this foundation before adding more sales volume or commitments.');
 return out;
}
